site_name: MkDocs Material Template
site_url: https://nodesautomations.com/Template_MkDocs/

theme:
  name: material

nav:
  - Home: Index.md
  - Typography: Typography.md
  - Configuration: Configuration.md
