site_name: MkDocs
site_url: https://nodesautomations.com/Template_MkDocs/

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode

nav:
  - Home: index.md
  - Typography: Typography.md
  - Configuration: Configuration.md

# Footer social links
extra:
  social:
    - icon: fontawesome/brands/globe
      link: https://www.nodesautomations.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnrjW31os9P6_MtSZXt6o-g
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/NodesAutomations