site_name: Sample Documentation
site_url: https://your-github-username.github.io/Template_MkDocs/

theme:
  name: material

nav:
  - Home: Index.md
  - Typography: Typography.md
  - Configuration: Configuration.md
